# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afdeafd46504b52d9799210dcce32cadcc055267a78355d5a05f699b921e0eb9f35b2b17366bd7c69ac624477e8ae61a280ad283fa3b7793c698062768b85fed

test:
  secret_key_base: 6b67850fef162651dfa71a02d6647306b8e29af57a82215162f857b73a5e8231d02635bb7901e83c6ea973f858b8d97927b719ff20d4088e18c7c09262d201e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
